      // exemple de DS contenant :                                                                  
       //   - une ds avec parametres entrée                                                         
       //   - une ds avec parametres sortie                                                         
                                                                                                    
       dcl-ds cnomcliDS_template qualified;                                                         
         // entrée                                                                                  
         numCliChar char(5);                                                                        
       end-ds;                                                                                      
                                                                                                    
                                                                                                     